#!/bin/sh

cat <<CHECKLIST
\033[0;31m====================
CHECK FOLLOWING CONDITIONS BEFORE PUSH
1. Test your modification in development/staging environment
2. View your diff
====================\033[0m
CHECKLIST

# Capture keyboard input
exec < /dev/tty

read -p "view diff in browser? [YyNn]" yn
case $yn in
  [Yy] | "yes" | "Yes" | "YES" )
    BRANCH=$(git rev-parse --abbrev-ref HEAD)
    render-diff origin/$BRANCH | browser
    ;;
  * ) break ;;
esac

read -p "...checked? [YyNn]" yn
case $yn in
  [Yy] | "yes" | "Yes" | "YES" ) break ;;
  [Nn] | "no" | "No" | "NO" ) exit 1 ;;
  * )
    echo "yes or no"
    exit 1
    ;;
esac
