tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'go-delve/delve'
tap 'homebrew/boneyard'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/python'
tap 'homebrew/science'
tap 'homebrew/services'
tap 'neovim/neovim'
brew 'autoconf'
brew 'automake'
brew 'boost'
brew 'fd'
brew 'openssl', args: ['universal']
brew 'readline'
brew 'sqlite'
brew 'xz'
brew 'python3'
brew 'boost-python', args: ['with-python3', 'without-python']
brew 'browser'
brew 'cmake'
brew 'coreutils'
brew 'cpanminus'
brew 'direnv'
brew 'eigen'
brew 'jpeg', args: ['universal']
brew 'libpng', args: ['universal']
brew 'libtiff', args: ['universal']
brew 'erlang'
brew 'flow'
brew 'freetype', args: ['universal']
brew 'fontconfig', args: ['universal']
brew 'fswatch'
brew 'mpfr'
brew 'libmpc'
brew 'gcc'
brew 'gd', args: ['universal']
brew 'gettext'
brew 'git'
brew 'ghq'
brew 'git-extras'
brew 'git-flow'
brew 'go'
brew 'libtool', args: ['universal']
brew 'graphicsmagick'
brew 'graphviz'
brew 'httpie'
brew 'hub'
brew 'perl'
brew 'imagemagick'
brew 'jq'
brew 'libevent'
brew 'python'
brew 'libxml2'
brew 'libyaml'
brew 'msgpack'
brew 'mysql'
brew 'numpy'
brew 'openexr'
brew 'pcre'
brew 'peco'
brew 'pkg-config'
brew 'postgresql'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'ruby-build'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'rename'
brew 'rlwrap'
brew 'ruby'
brew 'shellcheck'
brew 'tag'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'vim'
brew 'watchman'
brew 'yarn'
brew 'zsh'
brew 'go-delve/delve/delve'
brew 'homebrew/science/opencv'
brew 'neovim/neovim/neovim'
cask 'atom'
cask 'bettertouchtool'
cask 'dropbox'
cask 'flux'
cask 'google-japanese-ime'
cask 'karabiner'
cask 'kindle'
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'seil'
cask 'sourcetree'
cask 'vagrant'
cask 'virtualbox'
mas 'Patina', id: 942568098
mas 'DrCleanerPro', id: 1037994372
mas 'Key Codes', id: 414568915
mas 'Install macOS Sierra', id: 1127487414
mas 'ToyViewer', id: 414298354
mas 'Xcode', id: 497799835
mas 'ForkLift', id: 412448059
mas 'Microsoft OneNote', id: 784801555
mas 'Alternote', id: 974971992
