tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/boneyard'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/python'
tap 'homebrew/science'
tap 'homebrew/services'
tap 'neovim/neovim'
cask 'xquartz'
brew 'autoconf'
brew 'automake'
brew 'browser'
brew 'cmake'
brew 'coreutils'
brew 'cpanminus'
brew 'direnv'
brew 'dos2unix'
brew 'eigen'
brew 'openssl', args: ['universal']
brew 'jpeg', args: ['universal']
brew 'libpng', args: ['universal']
brew 'libtiff', args: ['universal']
brew 'wxmac'
brew 'erlang'
brew 'flow'
brew 'freetype', args: ['universal']
brew 'fontconfig', args: ['universal']
brew 'fswatch'
brew 'gmp'
brew 'isl'
brew 'mpfr'
brew 'libmpc'
brew 'gcc'
brew 'gd', args: ['universal']
brew 'gdbm'
brew 'gettext'
brew 'git'
brew 'ghq'
brew 'git-extras'
brew 'git-flow'
brew 'git-secrets'
brew 'go'
brew 'libtool', args: ['universal']
brew 'graphicsmagick'
brew 'graphviz'
brew 'readline'
brew 'sqlite'
brew 'xz'
brew 'python3'
brew 'httpie'
brew 'hub'
brew 'ilmbase'
brew 'perl'
brew 'imagemagick'
brew 'jasper', args: ['universal']
brew 'jemalloc'
brew 'oniguruma'
brew 'jq'
brew 'libevent'
brew 'libusb', args: ['universal']
brew 'libusb-compat', args: ['universal']
brew 'libgphoto2', args: ['universal']
brew 'libicns', args: ['universal']
brew 'libtermkey'
brew 'libuv'
brew 'libvterm'
brew 'python'
brew 'libxml2'
brew 'libyaml'
brew 'little-cms2', args: ['universal']
brew 'makedepend'
brew 'msgpack'
brew 'mysql'
brew 'node'
brew 'numpy'
brew 'openexr'
brew 'pandoc'
brew 'pcre'
brew 'passenger'
brew 'peco'
brew 'pkg-config'
brew 'postgresql'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'ruby-build'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'rename'
brew 'rlwrap'
brew 'ruby'
brew 'sane-backends', args: ['universal']
brew 'shellcheck'
brew 'tag'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'unibilium'
brew 'unixodbc'
brew 'vim'
brew 'watchman'
brew 'wine'
brew 'yarn'
brew 'zsh'
brew 'homebrew/boneyard/rsense'
brew 'homebrew/science/opencv'
brew 'neovim/neovim/neovim'
cask 'atom'
cask 'bettertouchtool'
cask 'dropbox'
cask 'evernote'
cask 'flux'
cask 'google-japanese-ime'
cask 'karabiner'
cask 'kindle'
cask 'lastpass'
cask 'otto'
cask 'pixate-studio'
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'seil'
cask 'skitch'
cask 'sourcetree'
cask 'terraform'
cask 'vagrant'
cask 'virtualbox'
cask 'zazu'
