[tools]
node = "24.11.1"

[tasks.install]
description = "Install"
run = "pnpm install"

[tasks."pkg:update"]
description = "Interactive package update"
raw = true
run = "pnpm update --recursive --latest --interactive"

