# git {{{
### ref: [【翻訳】Gitコマンドラインショートカット](http://postd.cc/git-command-line-shortcuts/)
alias ga='git add'
alias gaA='git add -A'
alias gb='git branch'
alias gbd='git branch -d '
alias gc='git commit'
alias gca='git commit --amend'
alias gcm='git commit -m'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcom='git checkout master'
alias gcp='git commit --patch'
alias gd='git diff'
alias gdH1='git diff HEAD~'
alias gdH='git diff HEAD'
alias gi='git init'
alias gld='git log --pretty=format:"%h %ad %s" --date=short --all'
alias glg='git log --graph --oneline --decorate --all'
alias glo='git log'
alias gm='git merge --no-ff'
alias gpic='git cherry-pick'
alias gpul='git pull'
alias gpus='git push'
alias greb='git rebase'
alias gres='git reset'
alias grev='git revert'
alias gs='git status'
alias gss='git status -s'
alias gst='git stash'
alias gstd='git stash drop'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gt='git tag'
# }}}

# vim:set ft=zsh:
