# mise configuration for runtime version management
# https://mise.jdx.dev/configuration.html

[tools]
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:ccmanager" = "latest"
"npm:diff-so-fancy" = "latest"
"npm:pnpm" = "latest"
"npm:yarn" = "latest"
gitui = "latest"
go = "latest"
node = "24"
usage = "latest"
watchexec = "latest"

[settings]
# Enable legacy version files (.node-version, .python-version, etc.)
legacy_version_file = true
# Always keep downloads to avoid re-downloading
always_keep_download = true
# Enable idiomatic version file support for Python tools
idiomatic_version_file_enable_tools = ["python"]
